# **Rank the top k nodes based on node score**

In [ ]:
# Rank the top k nodes based on node score
import pandas as pd

df=pd.read_csv("/content/gdrive/MyDrive/SNA/Results/normalized_results.csv")

ids=df['Id'].to_list()
scores=df['score'].to_list()
temp=dict()
for i in range(len(ids)):
    temp[ids[i]]=scores[i]

kresults=[[204054],[7018, 204004, 204054],[204004, 7018, 110028, 204054, 202109],[204004, 107177, 7018, 11115, 110028, 108172, 106191, 204146, 204054, 9905111, 110108, 202109],[7170, 203018, 108172, 204054, 110108, 204189, 205089, 201253, 107177, 112045, 8241, 12210, 3136, 202179, 5067, 110028, 106191, 206038, 
9905111, 203101, 204004, 7018, 11115, 204144, 204146, 111093, 202109, 203134],[7170, 6023, 5127, 8074, 203018, 108172, 9907086, 204054, 110108, 204189, 205089, 201253, 107177, 205101, 112045, 8241, 12210, 3136, 202179, 5067, 110028, 106191, 3025, 206038, 9905111, 203101, 110050, 204004, 7018, 11115, 204144, 204146, 111093, 202109, 203134]]

for result in kresults[1:2]:
    result.sort(key=lambda i:temp[i],reverse=True)
    print(result)

# **Find all the nodes for a given k value**

In [ ]:
import pandas as pd

rankings=pd.read_csv("/content/gdrive/MyDrive/SNA/Results/rankings.csv")
df=pd.read_csv("/content/gdrive/MyDrive/SNA/Results/normalized_results.csv")

for k in range(1950,2250,250):
    filept=dict()
    nodes=set()
    for i in range(1,14):
        nodes=nodes.union(set(rankings[rankings.columns[i]].to_list()[0:k]))
    newframe=df[df['Id'].isin(list(nodes))]
    newframe.to_csv("/content/gdrive/MyDrive/SNA/Results/graph_"+str(k)+".csv")